### PR TITLE
Abstract references to bepinexconfig out.

### PR DESCRIPTION
**Pull request by Bubbet**
I'm writing a mod that is basically config files but you can use zio filesystems, which means steam cloud. To write the risk of options side I need to abstract references to ConfigEntryBase because my type does not derive from that.

### CODE REVIEW

**Comment by Bubbet** [comment]
Another thing i came across while working on this is your slider code is pretty slow, because it triggers saves every frame when dragging them. Not sure what you can do about that but it'd be nice if you did something.

**Comment by Bubbet** [comment]
https://github.com/Bubbet/Risk-Of-Rain-Mods/tree/master/ZioRiskOfOptions Here is the mod i've made using this pr.

**Comment by Rune580** [comment]
After precursory look, everything seems good. But I currently have sick brain so I'll give this another look through after my brain is done being dead.

**Comment by Rune580** [comment]
Also I know that slider code is slow, I could probably have it check its value changing before submitting, but it's mostly so volume sliders don't get shafted, if that makes sense. Having the slider only submit after the user lets go of control wouldn't work well for having live changes. I could probably add in a config for changing this behavior though.

**Comment by Bubbet** [comment]
There is a field in configfile to not save when updating the value. You could set that so it doesnt save to disk while scrubbing and then upon release set it back and set the value again.

**Comment by Rune580** [comment]
That could work. I'll add that to my todo list for after I'm sickn't. Override as in just provide a method to toggle serializing off of BaseOption?

**Comment by Bubbet** [comment]
Yeah something I can override to toggle the same thing but in my type.

**Comment by Rune580** [comment]
should be doable, added to todo list

**Pull request merged**
